In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("C:/FAKE NEWS DETECTOR/fake_news_dataset_4000_rows.csv")
df

,id,title,text,author,source,topic,publish_date,year,month,day,word_count,char_count,title_length,label
0,1,Miracle Cure Update 1,This article discusses Miracle Cure Update 1. ...,Guest Writer,ViralNow,Miracle Cure,2023-09-30,2023,9,30,32,219,21,0
1,2,Conspiracy Update 2,This article discusses Conspiracy Update 2. Ho...,Unknown Reporter,RumorTimes,Conspiracy,2024-07-29,2024,7,29,31,217,19,0
2,3,Technology Update 3,This article discusses Technology Update 3. Th...,Ayesha Khan,BBC News,Technology,2023-05-19,2023,5,19,29,210,19,1
3,4,Economy Update 4,This article discusses Economy Update 4. The i...,Fatima Noor,Al Jazeera,Economy,2023-09-09,2023,9,9,29,207,16,1
4,5,Conspiracy Update 5,This article discusses Conspiracy Update 5. Ho...,Anonymous,RumorTimes,Conspiracy,2024-09-03,2024,9,3,31,217,19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,Alien News Update 3996,This article discusses Alien News Update 3996....,Editor Desk,TruthExpose,Alien News,2023-07-19,2023,7,19,32,220,22,0
3996,3997,Technology Update 3997,This article discusses Technology Update 3997....,Fatima Noor,BBC News,Technology,2023-04-14,2023,4,14,29,213,22,1
3997,3998,Politics Update 3998,This article discusses Politics Update 3998. T...,Michael Brown,The Guardian,Politics,2024-08-09,2024,8,9,29,211,20,1
3998,3999,Alien News Update 3999,This article discusses Alien News Update 3999....,Anonymous,TruthExpose,Alien News,2023-02-16,2023,2,16,32,220,22,0
3999,4000,Celebrity Gossip Update 4000,This article discusses Celebrity Gossip Update...,Admin,ShockMedia,Celebrity Gossip,2024-06-02,2024,6,2,32,226,28,0

In [5]:
import os
os.listdir()

['.android',
 '.aws',
 '.azure',
 '.cache',
 '.copilot',
 '.cursor',
 '.docker',
 '.emulator_console_auth_token',
 '.git',
 '.git-for-windows-updater',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.local',
 '.matplotlib',
 '.ms-ad',
 '.node_repl_history',
 '.skiko',
 '.ssh',
 '.streamlit',
 '.VirtualBox',
 '.vscode',
 '.zenmap',
 '01_data_validation.ipynb',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Documents',
 'Downloads',
 'fake_news_dataset_4000_rows.csv',
 'fake_news_model.pkl',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'My Documents',
 'myproject',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{05d1d48e-d80f-11ef-907e-ca5547cb5c9d}.TM.blf',
 'NTUSER.DAT{05d1d48e-d80f-11ef-907e-ca5547cb5c9d}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{05d1d48e-d80f-11ef-907e-ca5547cb5c9d}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'tfidf_vectorizer.pkl',
 'Untitled Folder',
 'VirtualBox VMs',
 'WPS Cloud Files']

In [6]:
import pandas as pd

df = pd.read_csv("fake_news_dataset_4000_rows.csv")

df.head()

,id,title,text,author,source,topic,publish_date,year,month,day,word_count,char_count,title_length,label
0,1,Miracle Cure Update 1,This article discusses Miracle Cure Update 1. ...,Guest Writer,ViralNow,Miracle Cure,2023-09-30,2023,9,30,32,219,21,0
1,2,Conspiracy Update 2,This article discusses Conspiracy Update 2. Ho...,Unknown Reporter,RumorTimes,Conspiracy,2024-07-29,2024,7,29,31,217,19,0
2,3,Technology Update 3,This article discusses Technology Update 3. Th...,Ayesha Khan,BBC News,Technology,2023-05-19,2023,5,19,29,210,19,1
3,4,Economy Update 4,This article discusses Economy Update 4. The i...,Fatima Noor,Al Jazeera,Economy,2023-09-09,2023,9,9,29,207,16,1
4,5,Conspiracy Update 5,This article discusses Conspiracy Update 5. Ho...,Anonymous,RumorTimes,Conspiracy,2024-09-03,2024,9,3,31,217,19,0

In [7]:
df.isnull().sum()

id              0
title           0
text            0
author          0
source          0
topic           0
publish_date    0
year            0
month           0
day             0
word_count      0
char_count      0
title_length    0
label           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['label'].value_counts()

label
0    2009
1    1991
Name: count, dtype: int64

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [11]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Bala
[nltk_data]     Praneeth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Bala
[nltk_data]     Praneeth\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [12]:
df['content'] = df['title'] + " " + df['text']

In [13]:
import pandas as pd

df = pd.read_csv("fake_news_dataset_4000_rows.csv")
df.head()

,id,title,text,author,source,topic,publish_date,year,month,day,word_count,char_count,title_length,label
0,1,Miracle Cure Update 1,This article discusses Miracle Cure Update 1. ...,Guest Writer,ViralNow,Miracle Cure,2023-09-30,2023,9,30,32,219,21,0
1,2,Conspiracy Update 2,This article discusses Conspiracy Update 2. Ho...,Unknown Reporter,RumorTimes,Conspiracy,2024-07-29,2024,7,29,31,217,19,0
2,3,Technology Update 3,This article discusses Technology Update 3. Th...,Ayesha Khan,BBC News,Technology,2023-05-19,2023,5,19,29,210,19,1
3,4,Economy Update 4,This article discusses Economy Update 4. The i...,Fatima Noor,Al Jazeera,Economy,2023-09-09,2023,9,9,29,207,16,1
4,5,Conspiracy Update 5,This article discusses Conspiracy Update 5. Ho...,Anonymous,RumorTimes,Conspiracy,2024-09-03,2024,9,3,31,217,19,0

In [14]:
import re
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [41]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Bala
[nltk_data]     Praneeth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Bala
[nltk_data]     Praneeth\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [16]:
df['content'] = df['title'] + " " + df['text']

In [17]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [lemmatizer.lemmatize(word) 
             for word in words 
             if word not in stop_words]
    return " ".join(words)

In [18]:
df['clean_content'] = df['content'].apply(clean_text)

In [19]:
df[['content', 'clean_content']].head()

,content,clean_content
0,Miracle Cure Update 1 This article discusses M...,miracle cure update article discusses miracle ...
1,Conspiracy Update 2 This article discusses Con...,conspiracy update article discusses conspiracy...
2,Technology Update 3 This article discusses Tec...,technology update article discusses technology...
3,Economy Update 4 This article discusses Econom...,economy update article discusses economy updat...
4,Conspiracy Update 5 This article discusses Con...,conspiracy update article discusses conspiracy...

In [23]:
df[['clean_content', 'label']].to_csv(
    r"C:\FAKE NEWS DETECTOR\cleaned_fake_news_dataset.csv",
    index=False
)

In [24]:
import os
os.listdir(r"C:\FAKE NEWS DETECTOR")

['app.py',
 'cleaned_fake_news_dataset.csv',
 'fake_news_dataset_4000_rows.csv',
 'model']

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [26]:
X = df['clean_content']   # input text
y = df['label']           # output (0 = fake, 1 = real)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [28]:
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [29]:
print("Train shape:", X_train_tfidf.shape)
print("Test shape:", X_test_tfidf.shape)

Train shape: (3200, 92)
Test shape: (800, 92)

In [30]:
X_train_tfidf.shape, X_test_tfidf.shape

((3200, 92), (800, 92))

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [33]:
y_pred = model.predict(X_test_tfidf)

In [34]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       402
           1       1.00      1.00      1.00       398

    accuracy                           1.00       800
   macro avg       1.00      1.00      1.00       800
weighted avg       1.00      1.00      1.00       800

In [36]:
confusion_matrix(y_test, y_pred)

array([[402,   0],
       [  0, 398]])

In [37]:
import pickle

In [38]:
with open("fake_news_model.pkl", "wb") as file:
    pickle.dump(model, file)

In [39]:
with open("tfidf_vectorizer.pkl", "wb") as file:
    pickle.dump(tfidf, file)

In [40]:
import os
os.listdir()

['.android',
 '.aws',
 '.azure',
 '.cache',
 '.copilot',
 '.cursor',
 '.docker',
 '.emulator_console_auth_token',
 '.git',
 '.git-for-windows-updater',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.local',
 '.matplotlib',
 '.ms-ad',
 '.node_repl_history',
 '.skiko',
 '.ssh',
 '.streamlit',
 '.VirtualBox',
 '.vscode',
 '.zenmap',
 '01_data_validation.ipynb',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Documents',
 'Downloads',
 'fake_news_dataset_4000_rows.csv',
 'fake_news_model.pkl',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'My Documents',
 'myproject',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{05d1d48e-d80f-11ef-907e-ca5547cb5c9d}.TM.blf',
 'NTUSER.DAT{05d1d48e-d80f-11ef-907e-ca5547cb5c9d}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{05d1d48e-d80f-11ef-907e-ca5547cb5c9d}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'tfidf_vectorizer.pkl',
 'Untitled Folder',
 'VirtualBox VMs',
 'WPS Cloud Files']